definitions:
  models.PaymentBody:
    properties:
      Description:
        type: string
      PaymentMethodID:
        type: string
      Price:
        type: number
      SellerID:
        type: string
      StripeAccountID:
        type: string
      UserID:
        type: string
    required:
    - Description
    - PaymentMethodID
    - Price
    - SellerID
    - StripeAccountID
    - UserID
    type: object
  models.PaymentError:
    properties:
      error:
        type: string
    type: object
  models.PaymentResponse:
    properties:
      PaymentIntentID:
        type: string
    type: object
  models.RefundResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /payment:
    post:
      consumes:
      - application/json
      description: Make a card Payment in Stripe
      parameters:
      - description: Parameters
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.PaymentBody'
      produces:
      - application/json
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/models.PaymentResponse'
        "400":
          description: Failed to read body.
          schema:
            $ref: '#/definitions/models.PaymentError'
        "500":
          description: Failed to save payment information.
          schema:
            $ref: '#/definitions/models.PaymentError'
      summary: Card Payment
      tags:
      - Payment
  /refund/{payment_intent_id}:
    patch:
      consumes:
      - application/json
      description: Refunds a payment made through Stripe
      parameters:
      - description: Payment Intent ID
        in: path
        name: payment_intent_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Refund processed and recorded successfully.
          schema:
            $ref: '#/definitions/models.RefundResponse'
        "400":
          description: Payment has already been refunded.
          schema:
            $ref: '#/definitions/models.PaymentError'
        "404":
          description: Payment record not found.
          schema:
            $ref: '#/definitions/models.PaymentError'
        "500":
          description: Failed to update payment record as refunded.
          schema:
            $ref: '#/definitions/models.PaymentError'
      summary: Refund Payment
      tags:
      - Payment
swagger: "2.0"
