version: '3.8'

services:
  payment:
    build: ./Payment
    image: lactrodectus/payment_microservice:1.0
    restart: always
    ports:
      - "8080:8080"

  purchasestudyresource:
    build: ./PurchaseStudyResource
    image: lactrodectus/purchasestudyresource_complexms:1.0
    restart: always
    ports:
      - "5100:5100"

  studyresource:
    build: ./StudyResource
    image: lactrodectus/studyresource_microservice:1.0
    restart: always
    ports:
      - "8000:8000"

  user:
    build: ./User
    image: lactrodectus/user_microservice:1.0
    restart: always  
    ports:
      - "3000:3000"

  # amqpbroker:
  #   build: ./AMQPBroker
  #   # Add any necessary configuration for AMQPBroker

  # chat:
  #   build: ./Chat
  #   # Add any necessary configuration for Chat

  # error:
  #   build: ./Error
  #   # Add any necessary configuration for Error

  # notification:
  #   build: ./Notification
  #   # Add any necessary configuration for Notification

  # quiz:
  #   build: ./Quiz
  #   # Add any necessary configuration for Quiz

  # streaming:
  #   build: ./Streaming
  #   # Add any necessary configuration for Streaming
  
  # tutor:
  #   build: ./Tutor
  #   # Add any necessary configuration for Tutor  