version: '3.8'

networks:
  esd:

services:
  payment:
    build: ./Payment    
    restart: always
    ports:
      - "8080:8080"

  purchasestudyresource:
    build: ./PurchaseStudyResource    
    restart: always
    depends_on:
      - amqpbroker
    ports:
      - "5100:5100"
    networks:
      - esd

  studyresource:
    build: ./StudyResource
    restart: always
    ports:
      - "8000:8000"
    networks:
      - esd

  user:
    build: ./User
    restart: always
    ports:
      - "3000:3000"
    networks:
      - esd

  amqpbroker:
    build: ./AMQPBroker
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - esd
      
  # chat:
  #   build: ./Chat
  #   # Add any necessary configuration for Chat

  # error:
  #   build: ./Error
  #   # Add any necessary configuration for Error

  # notification:
  #   build: ./Notification
  #   # Add any necessary configuration for Notification

  # quiz:
  #   build: ./Quiz
  #   # Add any necessary configuration for Quiz

  # streaming:
  #   build: ./Streaming
  #   # Add any necessary configuration for Streaming

  # tutor:
  #   build: ./Tutor
  #   # Add any necessary configuration for Tutor  
