apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat
        image: chat-app:latest
        ports:
        - containerPort: 3000
        env:
          - name: AMQP_HOST
            value: rabbitmq # The service name of RabbitMQ in Kubernetes
          - name: AMQP_PORT
            value: "5672"
          # Add other required environment variables here
        # readinessProbe:
        #   httpGet:
        #     path: /api/health # Replace with an actual health check endpoint if you have one
        #     port: 3000
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /api/health # Replace with an actual health check endpoint if you have one
        #     port: 3000
        #   initialDelaySeconds: 15
        #   periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: chat-app
spec:
  selector:
    app: chat-app
  ports:
    - port: 3000
      targetPort: 3000
