apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  AWS_BUCKET_NAME: "tuitiondaddyappimages"
  AWS_DEFAULT_REGION: "ap-southeast-1"
  MONGO_URL: "mongodb://mongodb:27017"
  AMQP_URL: "amqp://rabbitmq"
  WEB_SOCKET_PORT: "3000"
  FILE_UPLOADER_PORT: "3001"
  DB_NAME: "chatApp"